Repository OZ-Coding-School/oz_02_collabo-002, pull requests merged in 2024-05, with the labels that each got.

#39 feat: 이미지 합성 및 다운로드 기능개발
  aif_group/package-lock.json
  aif_group/package.json
  aif_group/public/icons/누끼_블랙티셔츠 2.svg
  aif_group/public/images/aiImage2.png
  aif_group/public/images/aiImage3.png
  aif_group/public/images/t-shirt_black.png
  aif_group/public/images/t-shirt_white.png
  aif_group/src/containers/design/DesignHeader.tsx
  aif_group/src/containers/design/DesignPreviewBox.tsx
  aif_group/src/containers/design/DesignSelectBox.tsx
  aif_group/src/containers/design/DesignStartBox.tsx
  aif_group/src/containers/main/Header.tsx
  aif_group/src/utils/downloadImages.ts
Labels: ✨ Feature

#43 feat: 티셔츠 미리보기 swiper 개발, 설문완료 후 다운로드 기능 개발
  aif_group/package-lock.json
  aif_group/package.json
  aif_group/public/images/aiImage1.png
  aif_group/src/app/design/feedback/page.tsx
  aif_group/src/app/design/howtouse/page.tsx
  aif_group/src/app/design/layout.tsx
  aif_group/src/app/design/sampleImage/page.tsx
  aif_group/src/containers/design/DesignLoadingBox.tsx
  aif_group/src/containers/design/DesignPreviewBox.tsx
  aif_group/src/containers/main/AboutSection.tsx
  aif_group/src/containers/main/LastBanner.tsx
  aif_group/src/containers/modal/FeedbackModal.tsx
  aif_group/src/hooks/reduxHooks.ts
  aif_group/src/states/imageSlice.ts
  aif_group/src/states/store.ts
  aif_group/src/styles/globals.css
  aif_group/src/utils/drawSelectedImage.ts
Labels: ✨ Feature

#45 feat : ErrorAler t1,2 연결
  aif_group/src/app/design/page.tsx
  aif_group/src/containers/design/DesignPreviewBox.tsx
  aif_group/src/containers/design/DesignSelectBox.tsx
  aif_group/src/containers/design/DesignStartBox.tsx
  aif_group/src/containers/modal/ErrorAlert1.tsx
  aif_group/src/containers/modal/ErrorAlert2.tsx
  aif_group/src/containers/modal/InputAlert.tsx
Labels: ✨ Feature

#46 chore: 윈도우 css 추가, 티셔츠 미리보기 스와이프에 티셔츠 이미지 썸네일 추가
  aif_group/src/app/design/layout.tsx
  aif_group/src/app/design/page.tsx
  aif_group/src/app/layout.tsx
  aif_group/src/app/page.tsx
  aif_group/src/app/thanks/page.tsx
  aif_group/src/components/DesignStartButton.tsx
  aif_group/src/components/ThumbnailImage.tsx
  aif_group/src/components/feedbackModal/Question3.tsx
  aif_group/src/containers/design/DesignHeader.tsx
  aif_group/src/containers/design/DesignLoadingBox.tsx
  aif_group/src/containers/design/DesignPreviewBox.tsx
  aif_group/src/containers/design/DesignStartBox.tsx
  aif_group/src/containers/main/AboutSection.tsx
  aif_group/src/containers/main/HowToCustomSection.tsx
  aif_group/src/containers/main/MainBanner.tsx
  aif_group/src/containers/modal/FeedbackModal.tsx
  aif_group/src/containers/modal/InputAlert.tsx
  aif_group/src/hooks/reduxHooks.ts
  aif_group/src/styles/globals.css
  aif_group/tailwind.config.ts
Labels: 🎨 Html&css, ✨ Feature

#52 feat: 메인페이지 반응형 css 추가 완료
  aif_group/public/icons/about_icon.svg
  aif_group/public/icons/arrow_left.svg
  aif_group/public/icons/arrow_right.svg
  aif_group/public/icons/close_icon_mint.svg
  aif_group/public/icons/hamburger_icon.svg
  aif_group/public/icons/logo_mint.svg
  aif_group/public/icons/sample1.svg
  aif_group/public/images/main_banner_mobile.png
  aif_group/src/app/design/page.tsx
  aif_group/src/app/layout.tsx
  aif_group/src/app/page.tsx
  aif_group/src/components/DesignStartButton.tsx
  aif_group/src/components/ScrollUpButton.tsx
  aif_group/src/components/SideNavigationMenu.tsx
  aif_group/src/containers/design/DesignHeader.tsx
  aif_group/src/containers/design/DesignPreviewBox.tsx
  aif_group/src/containers/main/AIImageSection.tsx
  aif_group/src/containers/main/AboutSection.tsx
  aif_group/src/containers/main/Footer.tsx
  aif_group/src/containers/main/Header.tsx
  aif_group/src/containers/main/HowToCustomSection.tsx
  aif_group/src/containers/main/LastBanner.tsx
  aif_group/src/containers/main/MainBanner.tsx
  aif_group/src/containers/main/MobileMainBanner.tsx
  aif_group/src/containers/modal/InputAlert.tsx
  aif_group/src/styles/globals.css
  aif_group/tailwind.config.ts
Labels: 🎨 Html&css

#66 feat: 페이지 이동 전 경고 이벤트 추가
  aif_group/src/app/design/page.tsx
  aif_group/src/app/thanks/page.tsx
  aif_group/src/components/SideNavigationMenu.tsx
  aif_group/src/containers/design/DesignHeader.tsx
  aif_group/src/containers/design/DesignLoadingBox.tsx
  aif_group/src/containers/design/DesignPreviewBox.tsx
  aif_group/src/containers/design/DesignSelectBox.tsx
  aif_group/src/containers/design/DesignStartBox.tsx
  aif_group/src/containers/main/Header.tsx
  aif_group/src/containers/main/MobileMainBanner.tsx
  aif_group/src/containers/modal/ErrorAlert2.tsx
  aif_group/src/containers/modal/FeedbackModal.tsx
  aif_group/src/hooks/useImages.ts
  aif_group/src/hooks/usePreventMoves.ts
  aif_group/src/hooks/useSelectImage.ts
  aif_group/src/hooks/useShowBox.ts
  aif_group/src/styles/globals.css
  aif_group/src/types/designSelectBoxType.ts
  aif_group/src/utils/downloadImages.ts
Labels: 🔨 Refactor, ✨ Feature
